### ISSUE TITLE
List: Rename graphic/meta class modifiers

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#536]
Change as per `material-components-web` v0.28.0
reference: https://github.com/material-components/material-components-web/pull/1716

- [ ] Rename `mdc-list-item__start-detail` css class to `mdc-list-item__graphic`
- [ ] Rename `mdc-list-item__end-detail` css class to `mdc-list-item__meta`
- [ ] Update unit tests
